[package]
name = "sudoku-solver"
version = "0.2.0"
authors = ["Rrogntudju"]
edition = "2018"

[lib]
name = "libsudokusolver"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "*"
features = ["extension-module"]

[dependencies.ahash]
version = "0.7"

[profile.release]
lto = "fat" 
codegen-units = 1